apiVersion: compliance.openshift.io/v1alpha1
kind: ComplianceSuite
metadata:
  name: rhcos-compliancesuite
spec:
  autoApplyRemediations: false
  schedule: "5 * * * *"
  scans:
    - name: rhcos-workers-scan
      scanType: Node
      profile: xccdf_org.ssgproject.content_profile_moderate
      content: ssg-rhcos4-ds.xml
      contentImage: quay.io/complianceascode/ocp4:latest
      nodeSelector:
        node-role.kubernetes.io/worker: ""
